// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VacationManagement.Infrastructure.Persistence;

#nullable disable

namespace VacationManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601143046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VacationManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ana.silva@workflow.com",
                            Name = "Ana Silva",
                            PasswordHash = "",
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Email = "joao.pereira@workflow.com",
                            Name = "João Pereira",
                            PasswordHash = "",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 5,
                            Email = "joana.soares@workflow.com",
                            Name = "Joana Soares",
                            PasswordHash = "",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "marta.fernandes@workflow.com",
                            ManagerId = 2,
                            Name = "Marta Fernandes",
                            PasswordHash = "",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 4,
                            Email = "henrique.martins@workflow.com",
                            ManagerId = 5,
                            Name = "Henrique Martins",
                            PasswordHash = "",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("VacationManagement.Domain.Entities.VacationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Status", "StartDate", "EndDate");

                    b.ToTable("VacationRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 3,
                            EndDate = new DateOnly(2025, 8, 5),
                            Notes = "Primeiras férias do ano",
                            StartDate = new DateOnly(2025, 8, 1),
                            Status = "Approved"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 4,
                            EndDate = new DateOnly(2025, 8, 15),
                            Notes = "Viagem em família",
                            StartDate = new DateOnly(2025, 8, 10),
                            Status = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 2,
                            EndDate = new DateOnly(2025, 9, 12),
                            Notes = "Primeiras férias do ano",
                            StartDate = new DateOnly(2025, 9, 1),
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("VacationManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("VacationManagement.Domain.Entities.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("VacationManagement.Domain.Entities.VacationRequest", b =>
                {
                    b.HasOne("VacationManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("VacationRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("VacationManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Subordinates");

                    b.Navigation("VacationRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
